name: Build-and-Push-Docker-Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -f app/Dockerfile \
            -t $IMAGE_NAME:latest \
            -t ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:${{ github.sha }} \
            app

      - name: Push Docker Image (SHA Tag)
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image (Latest Tag)
        run: |
          docker tag \
            $IMAGE_NAME:latest \
            ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:latest

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:latest

      - name: Image Details
        run: |
          echo "Image pushed successfully:"
          echo "${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:${{ github.sha }}"
          echo "${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:latest"
